### ISSUE TITLE
How should we handle validation tasks common to both sbndcode and icaruscode?

### ISSUE THREAD

**Issue by chilge** [SBNSoftware/sbnci#19]
Could we introduce some base class with the common elements with experiment specific implementations on top? @rennney what was your experience in modifying existing modules for use with icaruscode? Is something we that could be done "easily"?

**Comment by rennney** [comment]
I have only one general comment, especially if modules are going to be generalized. Most of my issues came from sbnd modules being written with one module lable in mind. In some cases, it is unclear how to correctly add more labels and not break the logic; however, that might be due to my little experience with larsoft.

**Comment by chilge** [comment]
I am nearing completion of my implementation of a solution to this question. If you're interested, see [`feature/chilgenb_CommonCode`](https://github.com/SBNSoftware/sbnci/tree/feature/chilgenb_CommonCode).
